fragment HomeParts on Home {
  __typename
  title
  body
}

fragment PostsParts on Posts {
  __typename
  title
  date
  body
}

fragment NotesParts on Notes {
  __typename
  title
  body
}

fragment PhotosParts on Photos {
  __typename
  title
  image
  body
}

fragment AboutParts on About {
  __typename
  title
  body
}

fragment PagesParts on Pages {
  __typename
  title
  menu
  draft
  body
}

fragment SiteConfigParts on SiteConfig {
  __typename
  title
  baseURL
  theme
  params {
    __typename
    hero {
      __typename
      background_image
    }
    article {
      __typename
      readingTime
      linkToMarkup
    }
  }
  menu {
    __typename
    main {
      __typename
      identifier
      name
      url
      weight
    }
  }
}
